webquiz/admin/views.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from flask_login import login_required, current_user
from webquiz.admin.forms import QuizForm, QuestionForm, SearchForm, CategoryForm, QuizSelectForm
from webquiz.main.views import quizzes
from webquiz.models.QuizDB import QuizDB

admin = Blueprint('admin', __name__, template_folder='templates')

@admin.route('/')
@login_required
def home():
    if current_user.is_admin():
        with QuizDB() as db:
            quizzes = db.get_quizzes()
            for quiz in quizzes:
                quiz.questions = db.get_questions(quiz.id)
                
        return render_template('admin.html', 
                               user=current_user, 
                               quizzes=quizzes)
    else:
        return redirect(url_for('main.home'))
    
@admin.route('/add-quiz', methods=['GET', 'POST'])
@login_required
def create_quiz():
    if current_user.is_admin():
        form = QuizForm()
        if form.validate_on_submit():
            title = form.title.data

            with QuizDB() as db:
                id = db.create_quiz(title)
                quiz = db.get_quiz(id)
            
            if quiz:
                flash(f"Quizzen {title} opprettet", category='success')
                return redirect(url_for('admin.quiz', id=id))
            else:
                flash('Noe gikk galt', category='danger')

        if form.errors:
            for message in form.errors.values():
                flash(message, category='error')
        return render_template('forms/addQuiz.html', form=form)
    else:
        return redirect(url_for('main.home'))

@admin.route('/edit-quiz', methods=['GET', 'POST'])
@login_required
def update_quiz():
    if current_user.is_admin():
        id = request.args['id']
        form = QuizForm()

        if form.validate_on_submit():
            with QuizDB() as db:
                db.update_quiz(id, form.title.data)
            
            flash(f"Quizzen oppdatert", category='success')
            return redirect(url_for('admin.quiz', id=id))
        
        if form.errors:
            for message in form.errors.values():
                flash(message, category='error')

        with QuizDB() as db:
            quiz = db.get_quiz(id)
        
        form.title.data = quiz.title
        form.submit.label.text = "Lagre"
        return render_template('forms/editQuiz.html', form=form, id=id)

    else:
        return redirect(url_for('main.home'))

@admin.route('/delete/quiz', methods=['GET'])
@login_required
def delete_quiz():
    if current_user.is_admin():
        id = request.args['id']

        with QuizDB() as db:
            db.delete_quiz(id)
            flash('Quiz slettet', 'success')

        return redirect(url_for('admin.home'))

    else:
        return redirect(url_for('main.home'))
    
@admin.route('/quiz/results', methods=['GET'])
@login_required
def quiz_results():
    if current_user.is_admin():
        id = request.args['id']

        with QuizDB() as db:
            quiz = db.get_quiz(id)
            quizzes = db.get_user_quizzes_by_quiz(id)

            for q in quizzes:
                q.answers = db.get_answers_with_result(q.id)
                q.calculate_score()

        return render_template('quizResults.html', 
                               quizzes=quizzes, 
                               title=quiz.title, 
                               user=current_user)

    else:
        return redirect(url_for('main.home'))
    
@admin.route('/quiz/user_answers', methods=['GET'])
@login_required
def quiz_user_answers():
    if current_user.is_admin():
        id = request.args['id']

        with QuizDB() as db:
            user_quiz = db.get_user_quiz(id)
            user_quiz.questions = db.get_questions(user_quiz.quiz)
            user_quiz.answers = db.get_answers_with_result(id)
            user_quiz.calculate_score()    

        return render_template('userAnswer.html', 
                               quiz=user_quiz, 
                               answers=len(user_quiz.answers),
                               user=current_user)

    else:
        return redirect(url_for('main.home'))
    
@admin.route('/quiz', methods=['GET'])
@login_required
def quiz():
    if current_user.is_admin():
        id = request.args['id']

        with QuizDB() as db:
            quiz = db.get_quiz(id)
            quiz.questions = db.get_questions(id)

        return render_template('adminQuiz.html', quiz=quiz, user=current_user)
    else:
        return redirect(url_for('main.home'))

@admin.route('/activate', methods=['GET'])
@login_required
def activate():
    if current_user.is_admin():
        id = request.args['id']
        status = request.args['status']
        status_text = 'aktiv' if int(status) else 'ikke aktiv'

        with QuizDB() as db:
            db.update_status(id, status)
        
        flash(f'Status satt til {status_text}', 'success')
        return redirect(url_for('admin.quiz', id=id))
    else:
        return redirect(url_for('main.home'))

@admin.route('/add-question', methods=['GET', 'POST'])
@login_required
def create_question():
    if current_user.is_admin():
        form = QuestionForm()
        quiz_id = request.args['quiz_id']

        with QuizDB() as db:
            result = db.get_categories()
            form.category.choices = [(name[0], name[0]) for name in result]

        if form.validate_on_submit():
            multiple_choice = int(form.is_multiple_choice.data)
            with QuizDB() as db:
                id = db.create_question(category=form.category.data, 
                                        content=form.content.data, 
                                        multiple_choice=multiple_choice)
                if quiz_id:
                    db.create_quiz_question(quiz_id=quiz_id, question_id=id)
                
                db.create_choice(question_id=id, content=form.answer.data, is_correct=True)

                if multiple_choice:
                    for choice in form.choices:
                        if choice.content.data:
                            db.create_choice(question_id=id, 
                                             content=choice.content.data,
                                             is_correct=False)

            flash('Spørsmål lagt til', 'success')
            if quiz_id:
                return redirect(url_for('admin.quiz', id=quiz_id, user=current_user))
            else:
                return redirect(url_for('admin.question', user=current_user))
        return render_template('forms/addQuestion.html', form=form, quiz_id=quiz_id)
    
    else:
        return redirect(url_for('main.home'))
    
@admin.route('/edit-question', methods=['GET', 'POST'])
@login_required
def update_question():
    if current_user.is_admin():
        id = request.args['id']
        quiz_id = request.args['quiz']

        # get the form data
        with QuizDB() as db:
            question = db.get_question(id)
            answer = db.get_answer(id)
            alternatives = db.get_alternatives(id)
            categories = db.get_categories()

        choices = []
        for choice in alternatives:
            choices.append({'content': choice.content, 'choice_id': choice.id})

        form = QuestionForm(choices=choices)
        form.category.choices = [(name[0], name[0]) for name in categories]

        if form.validate_on_submit():
            multiple_choice = int(form.is_multiple_choice.data)

            with QuizDB() as db:
                db.update_question(id=id,
                                   category=form.category.data,
                                   content=form.content.data,
                                   is_multiple_choice=multiple_choice)
                answer = db.get_answer(question_id=id)
                db.update_choice(id=answer.id, content=form.answer.data)
                
                if multiple_choice:
                    for choice in form.choices:
                        choice_id, content = choice.choice_id.data, choice.content.data
                        if choice_id and content:
                            db.update_choice(choice_id, content)
                        elif content:
                            db.create_choice(id, content, False)
                        elif choice_id:
                            db.delete_choice(choice_id)
                else:
                    # delete choices if any
                    alternatives = db.get_alternatives(question_id=id)
                    for choice in alternatives:
                        db.delete_choice(choice.id)
            
            flash('Spørsmål oppdatert', 'success')
            if quiz_id:
                return redirect(url_for('admin.quiz', id=quiz_id))
            else:
                return redirect(url_for('admin.question_detail', id=id))

        form.id.data = question.id
        form.category.data = question.category
        form.content.data = question.content
        form.is_multiple_choice.data = question.is_multiple_choice
        form.answer.data = answer.content
        
        if quiz_id:
            return render_template('forms/editQuestion.html', form=form, quiz=quiz_id)
        else:
            return render_template('forms/editQuestion.html', form=form)

    else:
        return redirect(url_for('main.home'))

@admin.route('/view_question')
@login_required
def question_detail():
    if current_user.is_admin():
        id = request.args['id']

        with QuizDB() as db:
            question = db.get_question(id)
            question.answer = db.get_answer(id)
            question.choices = db.get_alternatives(id)
            question.quizzes = db.get_quizzes_by_question(id)

        return render_template('questionView.html', question=question, user=current_user)
    else:
        return redirect(url_for('main.home'))
    
@admin.route('/questions', methods=['GET', 'POST'])

webquiz/admin/templates/admin.html
{% extends "base.html" %}
{% block content %}
<section class="admin dashboard">
    {% if user %}
    <h2 class="text-large text-primary">Velkommen {{user.firstname}}</h2>
    {% endif %}
    <div class="intro">
        <h3>Quizzer</h3>
        <a href="{{url_for('admin.create_quiz')}}" class="btn btn-primary">Ny Quiz</a>
    </div>
    {% if quizzes %}
    <table class='table link-table'>
        <thead>
            <tr>
                <th>Quiz</th>
                <th>Antall spørsmål</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for q in quizzes %}
            <tr class="{{'active' if q.is_active else ''}}">
                <td>
                    <a href="{{url_for('admin.quiz', id=q.id)}}" class="quiz-link">{{q.title}}</a>
                </td>
                <td>{{q.get_number_of_questions()}}</td>
                <td>
                    {% if q.is_active%}
                    <span class="status bg-success">Aktiv</span>
                    {% else %}
                    <span class="status bg-danger">Ikke Aktiv</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <p>Ingen quizzer i databasen</p>
    {% endif %}
</section>
{% endblock %}

webquiz/admin/templates/adminQuestion.html
!{% extends "base.html" %}
{% block content %}
<div class="admin-question">
    <header>
        <h2 class="text-large text-primary">Spørsmålsbank</h2>
        <div>
            <a href="{{url_for('admin.create_category')}}" class="btn btn-primary">Ny kategori</a>
        </div>
    </header>
    <form class="search" method="POST" action={{url_for('admin.question')}}>
        <div class="search-text">
            {{form.search(placeholder="Søk etter spørsmål")}}
            {{form.submit(class="search-btn")}}
        </div>
        <div>
            {{form.category}}
        </div>
    </form>
    {% if questions %}
    <section class="questions">
        <table class='table link-table'>
            <thead>
                <tr>
                    <th>Spørsmål</th>
                    <th>Svar</th>
                    <th>Kategorie</th>
                </tr>
            </thead>
            <tbody>
                {% for q in questions %}
                <tr>
                    <td>
                        <a href="{{url_for('admin.question_detail', id=q.id)}}" class="quiz-link">{{q.content}}</a>
                    </td>
                    <td>{{q.answer.content}}</td>
                    <td class='hide-sm'>{{q.category}}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% endif %}
    </section>
</div>
</div>

{% endblock %}

webquiz/admin/templates/adminQuiz.html
!{% extends "base.html" %}
{% block content %}
{% if quiz %}
<section class="quiz">
    <h2 class="text-large text-primary">Quiz: {{quiz.title}}</h2>
    <div class="info">
        <div class="btn-container">
            <a class="btn btn-primary" href="{{url_for('admin.quiz_results', id=quiz.id)}}">Se besvarelser</a>
            <a class="btn btn-primary" href="{{url_for('admin.create_question', quiz_id=quiz.id)}}">Nytt spørsmål</a>
            <a class="btn btn-secondary" href="{{url_for('admin.update_quiz', id=quiz.id)}}">Endre</a>
            <a class="btn btn-danger" href="{{url_for('admin.delete_quiz', id=quiz.id)}}">Slette</a>
        </div>
        {% if quiz.is_active%}
        <a href="{{url_for('admin.activate', id=quiz.id, status=0)}}" class="btn btn-danger">Deaktiver</a>
        {% else %}
        <a href="{{url_for('admin.activate', id=quiz.id, status=1)}}" class="btn btn-success">Aktiver</a>
        {% endif %}
    </div>
    {% if quiz.questions %}
    <table class='table'>
        <thead>
            <tr>
                <th>Spørsmål</th>
                <th>Kategorie</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for q in quiz.questions %}
            <tr>
                <td>{{q.content}}</td>
                <td class='hide-sm'>{{q.category}}</td>
                <td>
                    <a href={{url_for('admin.update_question', quiz=quiz.id, id=q.id)}}
                        class="btn btn-light">Rediger</a>
                    <a href={{url_for('admin.delete_quiz_question', quiz=quiz.id, id=q.id)}}
                        class="btn btn-danger">Slett
                        fra quiz</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% endif %}
</section>

{% endif %}
{% endblock %}

webquiz/admin/templates/choice.html
{% extends "base.html" %}
{% block content %}
<h2 class="text-large text-primary">Legg til svaralternativ</h2>
<form method="POST" action={{url_for('admin.choice', id=id)}}>
    {{form.hidden_tag()}}
    <div class="form-group">
        {{form.content.label}}
        {{form.content}}
    </div>
    {{form.submit(class="btn btn-primary")}}
</form>
{% endblock %}

webquiz/admin/templates/questionView.html
{% extends "base.html" %}
{% block content %}
<section class="question-detail">
    {% if question %}
    <div class="btn-container">
        <a class="btn btn-primary" href="{{url_for('admin.add_quiz_question', id=question.id)}}">Legg til quiz</a>
        <a class="btn btn-secondary" href="{{url_for('admin.update_question', quiz='', id=question.id)}}">Rediger</a>
        <a class="btn btn-danger" href="{{url_for('admin.delete_question', quiz='', id=question.id)}}">Slette</a>
    </div>
    <div>
        <h3>Kategori</h3>
        <p>{{question.category}}</p>
    </div>
    <div>
        <h3>Spørsmål</h3>
        <p>{{question.content}}</p>
    </div>
    <div>
        <h3>Riktig svar</h3>
        <p>{{question.answer.content}}</p>
    </div>
    {% if question.choices %}
    <div>
        <h3>Svaralternativer</h3>
        <ul>
            {% for choice in question.choices%}
            <li>
                <p>{{choice.content}}</p>

            </li>
            {% endfor%}
        </ul>
        {% endif %}
    </div>
    {% if question.quizzes %}
    <div>
        <h3>Tilhører quiz</h3>
        <ul>
            {% for quiz in question.quizzes%}
            <li>
                <p>{{quiz.title}}</p>

            </li>
            {% endfor%}
        </ul>
        {% endif %}
    </div>


    {% endif %}
</section>
{% endblock %}

webquiz/admin/templates/quiz.html
!{% extends "base.html" %}
{% block content %}
{% if quiz %}
<h2 class="text-large text-primary">Quiz: {{quiz.title}}</h2>
<div class="quiz">
    <div class="btn-container">
        <a class="btn btn-primary" href="{{url_for('admin.create_question', quiz_id=quiz.id)}}">Legg til spørsmål</a>
        <a class="btn btn-secondary" href="#">Endre</a>
        <a class="btn btn-danger" href="#">Slette</a>
    </div>
    {% if questions %}
    <div class="question">
        <table class='table'>
            <thead>
                <tr>
                    <th>Question</th>
                    <th>Category</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for q in questions %}
                <tr>
                    <td>{{q.content}}</td>
                    <td class='hide-sm'>{{q.category}}</td>
                    <td>
                        <a href={{url_for('admin.update_question', quiz=quiz.id, id=q.id)}}
                            class="btn btn-light">Rediger</a>
                        <a href={{url_for('admin.delete_question', quiz=quiz.id, id=q.id)}}
                            class="btn btn-danger">Slett</a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% endif %}
    </div>
</div>

{% endif %}
{% endblock %}

webquiz/admin/templates/quizResults.html
{% extends "base.html" %}
{% block content %}
{% if user %}
<section class="results">
    <h2 class="text-large text-primary">Besvarelser for {{title}}</h2>

    {% if quizzes %}

    <table class='table'>
        <thead>
            <tr>
                <th>Resultat</th>
                <th>Dato Tatt</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for q in quizzes %}
            <tr>
                <td>{{q.score}} %</td>
                <td>{{q.date_taken}}</td>
                <td>
                    <a href="{{url_for('admin.quiz_user_answers', id=q.id)}}" class="btn btn-primary">Se svar</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% else %}
    <p>Fant ingen besvarelser</p>
    {% endif %}
    {% endif %}
</section>
{% endblock %}

webquiz/admin/templates/quizView.html
{% extends "base.html" %}
{% block content %}
<section class="quiz_view">
    {% if quiz %}
    <h2 class="text-large text-primary">{{quiz.title}}</h2>
    {% for question in quiz.questions %}
    <div class="answer-result admin">
        <h3>Spørsmål</h3>
        <p>{{question.content}}</p>
        <h3>Riktig svar</h3>
        <p>{{question.answer.content}}</p>
        {% for answer in question.user_answers %}
        <ul>
            <li>bah</li>
        </ul>
        {% endfor %}
    </div>
    {% endfor %}
    {% endif %}
</section>

{% endblock %}

webquiz/admin/templates/userAnswer.html
{% extends "base.html" %}
{% block content %}
<section class="quiz">
    {% if quiz %}
    <h2 class="text-large text-primary">{{quiz.title}} ({{quiz.score}} %)</h2>
    <div class="info">
        <h3>Antall riktige svar: {{quiz.correct}} av {{answers}}</h3>
        <span>{{quiz.date_taken}}</span>
    </div>
    {% for i in range(0, answers)%}
    {% if quiz.answers[i].is_correct %}
    <div class="answer-result correct">
        <h3>Spørsmål {{i+1}}: Riktig!</h3>
        <p>{{quiz.answers[i].question_content}}</p>
        <p>{{quiz.answers[i].content}}</p>
    </div>
    {% else %}
    <div class="answer-result wrong">
        <h3>Spørsmål {{i+1}}: Feil</h3>
        <p>{{quiz.answers[i].question_content}}</p>
        <p>{{quiz.answers[i].content}}</p>
    </div>

    {% endif %}
    {% endfor %}
    {% endif %}

</section>
{% endblock %}